namespace Student
{
    public enum Specialty
    {
        Archeology,
        Archeometry,
        MuseumStudies,
        MobilityAndMigrations,
        InternationalBusinessRelations,
        MultilateralDiplomacy,
        InternationalSecurity,
        ArtificialIntelligence,
        InformationSystems,
        ITServicesAndProjects,
        ComputerGraphics,
        ComputerLinguistics,
        Economics,
        PoliticalEconomy,
        EconomicSociology,
        IndustrialBusiness,
        Entrepreneurship,
        RealEstateProperty,
        Finance,
        FinancialControl,
        AccountancyAndAnalysis,
        CommunicationNetworks,
        IndustrialAutomation,
        SystemsAndControl,
        RailwayEngineering,
        AirTransport,
        Mechanics,
        ComputerSystems,
    }
}
